import {Building2,CreditCard,LogOut,ReceiptText,Store,Trash2,TrendingUp} from "lucide-react";
import {redirect} from "next/navigation";
import {ensureSchema} from "@/db/client";
import {currentSession} from "@/lib/session";
import {PlatformOrders} from "@/components/platform-orders";
import {PlatformBusinesses} from "@/components/platform-businesses";

export default async function PlatformAdminPage(){const session=await currentSession();if(!session)redirect("/ingresar");if(session.platformRole!=="superadmin"){const destination=process.env.NODE_ENV==="production"?`https://${session.businessSlug}.tupedido360.co/admin`:`/store/${session.businessSlug}/admin`;redirect(destination)}const sql=await ensureSchema();
 const[businesses,[metrics],deletions,activeOrders]=await Promise.all([
  sql`SELECT b.id,b.name,b.slug,b.status,b.created_at AS "createdAt",s.status AS "subscriptionStatus",s.is_lifetime AS "isLifetime",s.trial_ends_at AS "trialEndsAt",(SELECT COUNT(*)::int FROM business_members bm WHERE bm.business_id=b.id AND bm.active) AS members,(SELECT COUNT(*)::int FROM orders o WHERE o.business_id=b.id AND o.deleted_at IS NULL) AS orders,(SELECT COALESCE(SUM(o.total_cop),0)::int FROM orders o WHERE o.business_id=b.id AND o.status<>'cancelled' AND o.deleted_at IS NULL) AS "salesCop" FROM businesses b JOIN subscriptions s ON s.business_id=b.id ORDER BY b.created_at DESC`,
  sql`SELECT (SELECT COUNT(*)::int FROM businesses) AS businesses,(SELECT COUNT(*)::int FROM businesses WHERE status IN('trial','active')) AS "activeBusinesses",(SELECT COUNT(*)::int FROM orders WHERE deleted_at IS NULL AND created_at>=date_trunc('day',timezone('America/Bogota',now())) AT TIME ZONE 'America/Bogota') AS "ordersToday",(SELECT COALESCE(SUM(total_cop),0)::int FROM orders WHERE deleted_at IS NULL AND status<>'cancelled') AS "totalSalesCop",(SELECT COALESCE(SUM(monthly_price_cop),0)::int FROM subscriptions WHERE NOT is_lifetime AND status IN('trialing','active')) AS "potentialMonthlyCop"`,
  sql`SELECT l.id,l.order_reference AS reference,l.reason,l.deleted_by_name AS "deletedByName",l.deleted_by_role AS "deletedByRole",l.deleted_at AS "deletedAt",l.tenant_purged_at AS "tenantPurgedAt",b.name AS "businessName",(l.order_snapshot->>'total_cop')::int AS "totalCop" FROM order_deletion_log l JOIN businesses b ON b.id=l.business_id ORDER BY l.deleted_at DESC LIMIT 100`,
  sql`SELECT o.id,o.reference,b.name AS "businessName",o.customer_name AS "customerName",o.total_cop AS "totalCop",o.created_at AS "createdAt" FROM orders o JOIN businesses b ON b.id=o.business_id WHERE o.deleted_at IS NULL AND o.status NOT IN('delivered','cancelled') ORDER BY o.created_at DESC LIMIT 100`
 ]);const money=(value:number)=>new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0}).format(value);
 return <main className="platform-admin"><header><div><span><Building2 size={22}/></span><div><strong>TuPedido360</strong><small>cPanel de Imagen Plus · {session.name}</small></div></div><form action="/api/auth/logout" method="post"><button><LogOut size={18}/>Cerrar sesión</button></form></header><section><div className="platform-heading"><div><p>Control general</p><h1>Resumen de la plataforma</h1></div><span><Store size={18}/>{Number(metrics.businesses)} negocios</span></div><div className="platform-metrics"><article><Store/><span>Negocios activos</span><strong>{Number(metrics.activeBusinesses)}</strong></article><article><ReceiptText/><span>Pedidos de hoy</span><strong>{Number(metrics.ordersToday)}</strong></article><article><TrendingUp/><span>Ventas registradas</span><strong>{money(Number(metrics.totalSalesCop))}</strong></article><article><CreditCard/><span>Mensualidad potencial</span><strong>{money(Number(metrics.potentialMonthlyCop))}</strong></article></div><div className="platform-heading platform-audit-heading"><div><p>Clientes de la plataforma</p><h1>Negocios registrados</h1></div></div><PlatformBusinesses businesses={businesses.map(row=>({id:String(row.id),name:String(row.name),slug:String(row.slug),status:String(row.status),subscriptionStatus:String(row.subscriptionStatus),isLifetime:Boolean(row.isLifetime),trialEndsAt:String(row.trialEndsAt),members:Number(row.members),orders:Number(row.orders),salesCop:Number(row.salesCop)}))}/><div className="platform-heading platform-audit-heading"><div><p>Operación en vivo</p><h1>Pedidos activos</h1></div><span>{activeOrders.length} pedidos</span></div><PlatformOrders orders={activeOrders.map(order=>({id:String(order.id),reference:String(order.reference),businessName:String(order.businessName),customerName:String(order.customerName),totalCop:Number(order.totalCop),createdAt:String(order.createdAt)}))}/><div className="platform-heading platform-audit-heading"><div><p>Auditoría permanente</p><h1>Pedidos eliminados</h1></div><span><Trash2 size={18}/>{deletions.length} registros</span></div><div className="platform-audit">{deletions.map(item=><article key={String(item.id)}><div><strong>{String(item.reference)}</strong><span>{String(item.businessName)}</span></div><div><b>{String(item.reason)}</b><span>{String(item.deletedByName)} · {String(item.deletedByRole)}</span></div><div><strong>{money(Number(item.totalCop??0))}</strong><span>{new Date(String(item.deletedAt)).toLocaleString("es-CO")}</span>{item.tenantPurgedAt&&<small>Retirado también por el dueño</small>}</div></article>)}{!deletions.length&&<p className="sales-empty">Todavía no existen pedidos eliminados.</p>}</div></section></main>}
