"use client";

import { Clock3, Eye, Palette, Save, UserRound } from "lucide-react";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ImageUpload } from "@/components/image-upload";

type Hour={weekday:number;enabled:boolean;openTime:string;closeTime:string};
type SettingsData={user:{name:string;email:string;phone:string};business:{name:string;slug:string;description:string;logoUrl:string;logoSize:number;primaryColor:string;accentColor:string;address:string;publicPhone:string;whatsapp:string};hours:Hour[];role:string};
const roleNames:Record<string,string>={owner:"Dueño",admin:"Administrador",cashier:"Caja",kitchen:"Cocina",waiter:"Mesero"};
const dayNames=["Lunes","Martes","Miércoles","Jueves","Viernes","Sábado","Domingo"];
const defaultHours=()=>dayNames.map((_,weekday)=>({weekday,enabled:weekday<6,openTime:"08:00",closeTime:"22:00"}));

export function SettingsManager(){
  const router=useRouter();
  const[data,setData]=useState<SettingsData|null>(null);const[tab,setTab]=useState<"profile"|"business">("profile");const[error,setError]=useState("");const[success,setSuccess]=useState("");const[saving,setSaving]=useState(false);const[logoUrl,setLogoUrl]=useState("");const[hours,setHours]=useState<Hour[]>(defaultHours);
  const load=useCallback(async()=>{const response=await fetch("/api/settings");const result=await response.json();if(response.ok){setData(result);setLogoUrl(result.business.logoUrl);setHours(result.hours.length===7?result.hours:defaultHours())}else setError(result.error)},[]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
  async function request(payload:Record<string,unknown>,message:string){setSaving(true);setError("");setSuccess("");const response=await fetch("/api/settings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)setError(result.error);else{setSuccess(message);await load();router.refresh()}setSaving(false)}
  async function submit(event:FormEvent<HTMLFormElement>,action:string){event.preventDefault();const form=new FormData(event.currentTarget);await request({action,...Object.fromEntries(form.entries())},"Cambios guardados correctamente.")}
  if(!data)return <div className="catalog-loading">Cargando configuración...</div>;
  return <div className="settings-manager"><div className="settings-tabs"><button className={tab==="profile"?"active":""} onClick={()=>setTab("profile")}><UserRound size={18}/>Mi perfil</button>{["owner","admin"].includes(data.role)&&<button className={tab==="business"?"active":""} onClick={()=>setTab("business")}><Palette size={18}/>Personalización</button>}</div>{error&&<p className="form-error">{error}</p>}{success&&<p className="settings-success">{success}</p>}{tab==="profile"?<ProfileForm data={data} saving={saving} submit={submit}/>:<div className="business-settings-stack"><BusinessForm data={data} logoUrl={logoUrl} setLogoUrl={setLogoUrl} saving={saving} submit={submit}/><HoursEditor hours={hours} setHours={setHours} saving={saving} save={()=>request({action:"updateHours",hours},"Horario guardado correctamente.")}/></div>}</div>;
}

function ProfileForm({data,saving,submit}:{data:SettingsData;saving:boolean;submit:(event:FormEvent<HTMLFormElement>,action:string)=>void}){return <form className="settings-form" onSubmit={event=>submit(event,"updateProfile")}><div className="settings-form-head"><div><h2>Mi perfil</h2><p>Información de tu cuenta personal.</p></div><span>{roleNames[data.role]??data.role}</span></div><div className="field-row"><label><span>Nombre completo</span><input name="name" defaultValue={data.user.name} required minLength={3}/></label><label><span>Celular</span><input name="phone" type="tel" defaultValue={data.user.phone} required minLength={7}/></label></div><label><span>Correo de acceso</span><input value={data.user.email} disabled/><small>El correo no se puede cambiar desde esta pantalla.</small></label><div className="settings-divider"><strong>Cambiar contraseña</strong><span>Déjalo vacío para conservar la actual.</span></div><div className="field-row"><label><span>Contraseña actual</span><input name="currentPassword" type="password" autoComplete="current-password"/></label><label><span>Nueva contraseña</span><input name="newPassword" type="password" minLength={8} autoComplete="new-password"/></label></div><button className="primary-compact settings-save" disabled={saving}><Save size={18}/>{saving?"Guardando...":"Guardar perfil"}</button></form>}

function BusinessForm({data,logoUrl,setLogoUrl,saving,submit}:{data:SettingsData;logoUrl:string;setLogoUrl:(value:string)=>void;saving:boolean;submit:(event:FormEvent<HTMLFormElement>,action:string)=>void}){const[logoSize,setLogoSize]=useState(data.business.logoSize||72);return <form className="settings-form" onSubmit={event=>submit(event,"updateBusiness")}><div className="settings-form-head"><div><h2>Personalización del negocio</h2><p>Estos datos aparecerán en el menú público.</p></div><a href={`https://${data.business.slug}.tupedido360.co`} target="_blank" rel="noreferrer"><Eye size={17}/>Ver tienda</a></div><label><span>Nombre del negocio</span><input name="name" defaultValue={data.business.name} required/></label><label><span>Descripción o frase del local</span><textarea name="description" defaultValue={data.business.description} rows={3} maxLength={300} placeholder="Ej. Antojos, sabor hecho con cariño"/><small>Esta frase aparecerá debajo del nombre en la barra del menú.</small></label><input name="logoUrl" type="hidden" value={logoUrl}/><ImageUpload label="Logo del negocio" value={logoUrl} onChange={setLogoUrl}/><label className="logo-size-control"><span>Tamaño del logo <b>{logoSize} px</b></span><input name="logoSize" type="range" min="48" max="96" step="2" value={logoSize} onChange={event=>setLogoSize(Number(event.target.value))}/><small>Desliza la barra para aumentar o reducir el logo del menú.</small></label><div className="color-fields"><label><span>Color principal</span><div><input name="primaryColor" type="color" defaultValue={data.business.primaryColor}/><input value={data.business.primaryColor} readOnly/></div></label><label><span>Color de acento</span><div><input name="accentColor" type="color" defaultValue={data.business.accentColor}/><input value={data.business.accentColor} readOnly/></div></label></div><label><span>Dirección</span><input name="address" defaultValue={data.business.address}/></label><div className="field-row"><label><span>Teléfono público</span><input name="publicPhone" type="tel" defaultValue={data.business.publicPhone}/></label><label><span>WhatsApp</span><input name="whatsapp" type="tel" defaultValue={data.business.whatsapp} placeholder="573001234567"/></label></div><button className="primary-compact settings-save" disabled={saving}><Save size={18}/>{saving?"Guardando...":"Guardar personalización"}</button></form>}

function HoursEditor({hours,setHours,saving,save}:{hours:Hour[];setHours:(hours:Hour[])=>void;saving:boolean;save:()=>void}){function change(index:number,values:Partial<Hour>){setHours(hours.map((hour,itemIndex)=>itemIndex===index?{...hour,...values}:hour))}return <section className="settings-form hours-editor"><div className="settings-form-head"><div><h2><Clock3 size={20}/>Horario de atención</h2><p>Define cuándo el negocio aparece abierto y recibe pedidos.</p></div></div><div className="hours-list">{hours.map((hour,index)=><div className={!hour.enabled?"disabled":""} key={hour.weekday}><label className="hours-toggle"><input type="checkbox" checked={hour.enabled} onChange={event=>change(index,{enabled:event.target.checked})}/><span>{dayNames[index]}</span></label>{hour.enabled?<><label><span>Abre</span><input type="time" value={hour.openTime} onChange={event=>change(index,{openTime:event.target.value})}/></label><label><span>Cierra</span><input type="time" value={hour.closeTime} onChange={event=>change(index,{closeTime:event.target.value})}/></label></>:<strong>Cerrado</strong>}</div>)}</div><button className="primary-compact settings-save" disabled={saving} onClick={save}><Save size={18}/>{saving?"Guardando...":"Guardar horario"}</button></section>}
