"use client";

import { Plus, UserRoundCheck, UserRoundX, X } from "lucide-react";
import { FormEvent, useCallback, useEffect, useState } from "react";

type Member = { id: string; name: string; email: string; phone: string; role: string; active: boolean };
const roleNames: Record<string,string> = { owner:"Dueño", admin:"Administrador", cashier:"Caja", kitchen:"Cocina", waiter:"Mesero" };

export function TeamManager() {
  const [members,setMembers]=useState<Member[]>([]); const [open,setOpen]=useState(false); const [error,setError]=useState(""); const [loading,setLoading]=useState(true);
  const load=useCallback(async()=>{const response=await fetch("/api/team");const result=await response.json();if(response.ok)setMembers(result.members);else setError(result.error);setLoading(false);},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[load]);
  async function action(payload:Record<string,unknown>){const response=await fetch("/api/team",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok){setError(result.error);return false;}await load();return true;}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);if(await action({action:"createEmployee",...Object.fromEntries(form.entries())}))setOpen(false);}
  return <div className="team-manager"><div className="manager-heading"><div><h2>Equipo del negocio</h2><p>Crea accesos independientes y asigna las herramientas de cada persona.</p></div><button className="primary-compact" onClick={()=>setOpen(true)}><Plus size={18}/>Nuevo empleado</button></div>{error&&<p className="form-error">{error}</p>}{loading?<div className="catalog-loading">Cargando equipo...</div>:<div className="member-grid">{members.map(member=><article key={member.id} className={!member.active?"disabled":""}><span className="member-avatar">{member.name.split(" ").map(part=>part[0]).slice(0,2).join("").toUpperCase()}</span><div><strong>{member.name}</strong><span>{member.email}</span><small>{roleNames[member.role]??member.role}</small></div>{member.role!=="owner"&&<button title={member.active?"Desactivar usuario":"Activar usuario"} onClick={()=>action({action:"toggleEmployee",id:member.id})}>{member.active?<UserRoundX size={18}/>:<UserRoundCheck size={18}/>}</button>}</article>)}</div>}{open&&<div className="editor-backdrop"><form className="product-editor" onSubmit={submit}><header><div><h2>Nuevo empleado</h2><p>La persona usará su correo y contraseña para trabajar.</p></div><button type="button" onClick={()=>setOpen(false)}><X size={20}/></button></header><label><span>Nombre completo</span><input name="name" required minLength={3}/></label><label><span>Correo</span><input name="email" type="email" required/></label><label><span>Celular</span><input name="phone" type="tel" minLength={7} required/></label><label><span>Cargo</span><select name="role" defaultValue="waiter"><option value="waiter">Mesero</option><option value="admin">Administrador</option><option value="cashier">Caja</option><option value="kitchen">Cocina</option></select></label><label><span>Contraseña temporal</span><input name="password" type="password" minLength={8} required/></label><footer><button className="secondary-action" type="button" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary-compact">Crear acceso</button></footer></form></div>}</div>;
}
