import { compare, hash } from "bcryptjs";
import { NextResponse } from "next/server";
import { ensureSchema } from "@/db/client";
import { createSessionToken, currentSession, sessionCookie } from "@/lib/session";

async function context(){const session=await currentSession();if(!session?.businessId||!session.userId)return null;return{session,businessId:session.businessId,userId:session.userId,sql:await ensureSchema()}}
export async function GET(){const auth=await context();if(!auth)return NextResponse.json({error:"Sesión no autorizada."},{status:401});const[[user],[business],hours,subscription]=await Promise.all([auth.sql`SELECT name,email,phone FROM users WHERE id=${auth.userId}`,auth.sql`SELECT name,slug,description,logo_url AS "logoUrl",logo_size AS "logoSize",accepting_orders AS "acceptingOrders",primary_color AS "primaryColor",accent_color AS "accentColor",address,public_phone AS "publicPhone",whatsapp FROM businesses WHERE id=${auth.businessId}`,auth.sql`SELECT weekday,enabled,to_char(open_time,'HH24:MI') AS "openTime",to_char(close_time,'HH24:MI') AS "closeTime" FROM business_hours WHERE business_id=${auth.businessId} ORDER BY weekday`,auth.sql`SELECT status,is_lifetime AS "isLifetime",monthly_price_cop AS "monthlyPriceCop",trial_ends_at AS "trialEndsAt",current_period_ends_at AS "currentPeriodEndsAt" FROM subscriptions WHERE business_id=${auth.businessId}`]);return NextResponse.json({user,business,hours,subscription:subscription[0]??null,role:auth.session.role})}

export async function POST(request:Request){
 const auth=await context();if(!auth)return NextResponse.json({error:"Sesión no autorizada."},{status:401});const body=await request.json().catch(()=>null) as Record<string,unknown>|null;if(!body)return NextResponse.json({error:"Solicitud inválida."},{status:400});
 if(body.action==="updateProfile"){const name=String(body.name??"").trim();const phone=String(body.phone??"").trim();if(name.length<3||name.length>100||phone.length<7||phone.length>30)return NextResponse.json({error:"Revisa tu nombre y celular."},{status:400});const currentPassword=String(body.currentPassword??"");const newPassword=String(body.newPassword??"");let sessionVersion=auth.session.sessionVersion??0;if(newPassword){if(newPassword.length<8||newPassword.length>128||!currentPassword||currentPassword.length>128)return NextResponse.json({error:"La nueva contraseña debe tener entre 8 y 128 caracteres."},{status:400});const[user]=await auth.sql`SELECT password_hash FROM users WHERE id=${auth.userId}`;if(!user||!await compare(currentPassword,String(user.password_hash)))return NextResponse.json({error:"La contraseña actual no es correcta."},{status:401});const[updated]=await auth.sql`UPDATE users SET name=${name},phone=${phone},password_hash=${await hash(newPassword,12)},session_version=session_version+1 WHERE id=${auth.userId} RETURNING session_version`;sessionVersion=Number(updated.session_version)}else await auth.sql`UPDATE users SET name=${name},phone=${phone} WHERE id=${auth.userId}`;const response=NextResponse.json({ok:true});response.cookies.set(sessionCookie.name,createSessionToken({...auth.session,name,sessionVersion}),sessionCookie.options);return response}
 if(body.action==="updateBusiness"){if(!["owner","admin"].includes(auth.session.role??""))return NextResponse.json({error:"No tienes permiso para personalizar el negocio."},{status:403});const name=String(body.name??"").trim();const description=String(body.description??"").trim().slice(0,300);const logoUrl=String(body.logoUrl??"").trim().slice(0,1000);const logoSize=Math.min(96,Math.max(48,Number(body.logoSize)||72));const primaryColor=String(body.primaryColor??"");const accentColor=String(body.accentColor??"");const address=String(body.address??"").trim().slice(0,200);const publicPhone=String(body.publicPhone??"").trim().slice(0,30);const whatsapp=String(body.whatsapp??"").replace(/\D/g,"").slice(0,20);const validLogo=!logoUrl||/^https?:\/\//i.test(logoUrl)||/^\/api\/media\/[0-9a-f-]{36}$/i.test(logoUrl);if(name.length<2||!/^#[0-9a-f]{6}$/i.test(primaryColor)||!/^#[0-9a-f]{6}$/i.test(accentColor)||!validLogo)return NextResponse.json({error:"Revisa el nombre, los colores y el logo."},{status:400});await auth.sql`UPDATE businesses SET name=${name},description=${description},logo_url=${logoUrl},logo_size=${logoSize},primary_color=${primaryColor},accent_color=${accentColor},address=${address},public_phone=${publicPhone},whatsapp=${whatsapp},updated_at=now() WHERE id=${auth.businessId}`;const response=NextResponse.json({ok:true});response.cookies.set(sessionCookie.name,createSessionToken({...auth.session,businessName:name}),sessionCookie.options);return response}
 if(body.action==="toggleOrders"){if(!["owner","admin"].includes(auth.session.role??""))return NextResponse.json({error:"No tienes permiso para pausar pedidos."},{status:403});const[business]=await auth.sql`UPDATE businesses SET accepting_orders=NOT accepting_orders,updated_at=now() WHERE id=${auth.businessId} RETURNING accepting_orders AS "acceptingOrders"`;return NextResponse.json({business})}
 if(body.action==="updateHours"){if(!["owner","admin"].includes(auth.session.role??""))return NextResponse.json({error:"No tienes permiso para editar el horario."},{status:403});const hours=Array.isArray(body.hours)?body.hours:[];if(hours.length!==7)return NextResponse.json({error:"El horario debe incluir los siete días."},{status:400});for(const[weekday,item]of hours.entries()){const row=item as Record<string,unknown>;const openTime=String(row.openTime??"");const closeTime=String(row.closeTime??"");if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(openTime)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(closeTime)||openTime>=closeTime)return NextResponse.json({error:"Revisa las horas de apertura y cierre."},{status:400});await auth.sql`INSERT INTO business_hours(business_id,weekday,enabled,open_time,close_time) VALUES(${auth.businessId},${weekday},${row.enabled!==false},${openTime},${closeTime}) ON CONFLICT(business_id,weekday) DO UPDATE SET enabled=excluded.enabled,open_time=excluded.open_time,close_time=excluded.close_time`}return NextResponse.json({ok:true})}
 return NextResponse.json({error:"Acción no reconocida."},{status:400})
}
