import { compare, hash } from "bcryptjs";
import { NextResponse } from "next/server";
import { ensureSchema } from "@/db/client";
import { createSessionToken, currentSession, sessionCookie } from "@/lib/session";

async function context() {
  const session=await currentSession();
  if(!session?.businessId||!session.userId)return null;
  return {session,businessId:session.businessId,userId:session.userId,sql:await ensureSchema()};
}

export async function GET(){const auth=await context();if(!auth)return NextResponse.json({error:"Sesión no autorizada."},{status:401});const[user]=await auth.sql`SELECT name,email,phone FROM users WHERE id=${auth.userId}`;const[business]=await auth.sql`SELECT name,slug,description,logo_url AS "logoUrl",logo_size AS "logoSize",primary_color AS "primaryColor",accent_color AS "accentColor",address,public_phone AS "publicPhone",whatsapp FROM businesses WHERE id=${auth.businessId}`;const hours=await auth.sql`SELECT weekday,enabled,to_char(open_time,'HH24:MI') AS "openTime",to_char(close_time,'HH24:MI') AS "closeTime" FROM business_hours WHERE business_id=${auth.businessId} ORDER BY weekday`;return NextResponse.json({user,business,hours,role:auth.session.role});}

export async function POST(request:Request){const auth=await context();if(!auth)return NextResponse.json({error:"Sesión no autorizada."},{status:401});const body=await request.json().catch(()=>null) as Record<string,unknown>|null;if(!body)return NextResponse.json({error:"Solicitud inválida."},{status:400});
  if(body.action==="updateProfile"){const name=typeof body.name==="string"?body.name.trim():"";const phone=typeof body.phone==="string"?body.phone.trim():"";if(name.length<3||phone.length<7)return NextResponse.json({error:"Revisa tu nombre y celular."},{status:400});const currentPassword=typeof body.currentPassword==="string"?body.currentPassword:"";const newPassword=typeof body.newPassword==="string"?body.newPassword:"";if(newPassword){if(newPassword.length<8||!currentPassword)return NextResponse.json({error:"La nueva contraseña debe tener al menos 8 caracteres."},{status:400});const[user]=await auth.sql`SELECT password_hash FROM users WHERE id=${auth.userId}`;if(!user||!await compare(currentPassword,String(user.password_hash)))return NextResponse.json({error:"La contraseña actual no es correcta."},{status:401});await auth.sql`UPDATE users SET name=${name},phone=${phone},password_hash=${await hash(newPassword,12)} WHERE id=${auth.userId}`;}else await auth.sql`UPDATE users SET name=${name},phone=${phone} WHERE id=${auth.userId}`;const response=NextResponse.json({ok:true});response.cookies.set(sessionCookie.name,createSessionToken({...auth.session,name}),sessionCookie.options);return response;}
  if(body.action==="updateBusiness"){if(!auth.session.role||!["owner","admin"].includes(auth.session.role))return NextResponse.json({error:"No tienes permiso para personalizar el negocio."},{status:403});const name=typeof body.name==="string"?body.name.trim():"";const description=typeof body.description==="string"?body.description.trim().slice(0,300):"";const logoUrl=typeof body.logoUrl==="string"?body.logoUrl.trim().slice(0,1000):"";const logoSize=Math.min(96,Math.max(48,Number(body.logoSize)||72));const primaryColor=typeof body.primaryColor==="string"?body.primaryColor:"";const accentColor=typeof body.accentColor==="string"?body.accentColor:"";const address=typeof body.address==="string"?body.address.trim().slice(0,200):"";const publicPhone=typeof body.publicPhone==="string"?body.publicPhone.trim().slice(0,30):"";const whatsapp=typeof body.whatsapp==="string"?body.whatsapp.replace(/\D/g,"").slice(0,20):"";const validLogo=!logoUrl||/^https?:\/\//i.test(logoUrl)||/^\/api\/media\/[0-9a-f-]{36}$/i.test(logoUrl);if(name.length<2||!/^#[0-9a-f]{6}$/i.test(primaryColor)||!/^#[0-9a-f]{6}$/i.test(accentColor)||!validLogo)return NextResponse.json({error:"Revisa el nombre, los colores y el logo."},{status:400});await auth.sql`UPDATE businesses SET name=${name},description=${description},logo_url=${logoUrl},logo_size=${logoSize},primary_color=${primaryColor},accent_color=${accentColor},address=${address},public_phone=${publicPhone},whatsapp=${whatsapp},updated_at=now() WHERE id=${auth.businessId}`;const response=NextResponse.json({ok:true});response.cookies.set(sessionCookie.name,createSessionToken({...auth.session,businessName:name}),sessionCookie.options);return response;}
  if(body.action==="updateHours"){if(!auth.session.role||!["owner","admin"].includes(auth.session.role))return NextResponse.json({error:"No tienes permiso para editar el horario."},{status:403});const hours=Array.isArray(body.hours)?body.hours:[];if(hours.length!==7)return NextResponse.json({error:"El horario debe incluir los siete días."},{status:400});for(const [weekday,item] of hours.entries()){const row=item as Record<string,unknown>;const openTime=String(row.openTime??"");const closeTime=String(row.closeTime??"");if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(openTime)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(closeTime)||openTime>=closeTime)return NextResponse.json({error:"Revisa las horas de apertura y cierre."},{status:400});await auth.sql`INSERT INTO business_hours(business_id,weekday,enabled,open_time,close_time) VALUES(${auth.businessId},${weekday},${row.enabled!==false},${openTime},${closeTime}) ON CONFLICT(business_id,weekday) DO UPDATE SET enabled=excluded.enabled,open_time=excluded.open_time,close_time=excluded.close_time`;}return NextResponse.json({ok:true});}
  return NextResponse.json({error:"Acción no reconocida."},{status:400});
}
